/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import Entity.tanggiam;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc.JDBC;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class GameClickUpAndDown extends javax.swing.JFrame {

    private JDBC jdbc;
    private tanggiam tanggiam;
    private boolean isButtonClicked = false;

    /**
     * Creates new form GameClickUpAndDown
     */
    public GameClickUpAndDown() throws ClassNotFoundException, SQLException, IOException {
        jdbc = new JDBC();
        try {
            jdbc.jdbcConnectDB();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        initComponents();
        show_databaseInJFieldText();
    }

    public void show_databaseInJFieldText() throws SQLException {
        int databaseTanggiam = jdbc.getTanggiam();
        jTextField1.setText(String.valueOf(databaseTanggiam));
    }

    public void increase() throws SQLException, ClassNotFoundException {
        int currentTanggiam = jdbc.getTanggiam();
        int newTanggiam = currentTanggiam + 1;
        jdbc.updateByID(newTanggiam);
        jTextField1.setText(String.valueOf(newTanggiam));
    }

    public void decrease() throws SQLException, ClassNotFoundException {
        int currentTanggiam = jdbc.getTanggiam();
        int newTanggiam = currentTanggiam - 1;
        jdbc.updateByID(newTanggiam);
        jTextField1.setText(String.valueOf(newTanggiam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Increase = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Decrease = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Increase.setText("Increase");
        Increase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Decrease.setText("Decrease");
        Decrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Increase, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Decrease)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Increase)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decrease))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void IncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseActionPerformed
        try {
            if (!isButtonClicked) {
                increase();
            } else {
                jdbc.jdbcDisconnectDB();
            }
               int value = Integer.parseInt(jTextField1.getText());
               if(value>0)
               {
                  Decrease.setEnabled(true);   
               }
        } catch (SQLException ex) {
            Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IncreaseActionPerformed

    private void DecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseActionPerformed
        try {
            if (!isButtonClicked) {
                decrease();
            } else {
                jdbc.jdbcDisconnectDB();
            }
            int value = Integer.parseInt(jTextField1.getText());
            if (value == 0) {
                Decrease.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DecreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameClickUpAndDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameClickUpAndDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameClickUpAndDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameClickUpAndDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GameClickUpAndDown().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(GameClickUpAndDown.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Decrease;
    private javax.swing.JButton Increase;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
